name: dchookspigot
version: '1.0.2+spigot'
main: com.github.pinmacaroon.dchookspigot.Dchookspigot
load: STARTUP
authors: [ pin ]
description: discord webhook thing
website: https://pinmacaroon.github.io/
